### ISSUE TITLE
html-postcss

### ISSUE THREAD

**Issue by ai** [RebelMail/html-autoprefixer#9]
Autoprefixer is just a PostCSS plugin. But we have many other [awesome plugins](https://github.com/postcss/postcss#plugins). For example, Bootstrap team want to migrate from Less to PostCSS.

So, maybe you want to create also `html-postcss`?

**Comment by elbuo8** [comment]
@motdotla @devinus I'm game.

**Comment by devinus** [comment]
@ai It would be great to have a way to run single rules through. Currently we have to do something really hacky: https://github.com/RebelMail/html-autoprefixer/blob/master/lib/main.js#L28

**Comment by ai** [comment]
@devinus this is why yoou should think about PostCSS API, not Autoprefixer ;).

```
postcss([ autoprefixer ]).process(element.attribs.style).css
```

**Comment by devinus** [comment]
Oh awesome! We'll have to test the performance of this. We came upon the current RegExp based approach because it was the fastest way to process. Calling autoprefixer many times was very slow. It's still really slow, but much less slower than running each set of rules through autoprefixer multiple times rather than just once. https://github.com/RebelMail/html-autoprefixer/blob/master/lib/main.js#L35
